import { describe, expect, it } from "vitest";
import * as fixtures from "./fixtures.js";

// Guards against drift from docs/DATA_MODEL.md: each fixture's key set must match
// the JSON example there exactly.
const expectedKeys: Record<string, string[]> = {
  countryProfileFixture: [
    "country_code",
    "admin_levels",
    "region_code_authority",
    "boundary_dataset_uri",
    "official_languages",
    "canonical_working_language",
    "currency",
    "citizen_auth_method",
    "policy_corpus_id",
    "data_residency_region",
    "privacy_regime",
  ],
  adminRegionFixture: [
    "region_id",
    "country_code",
    "level",
    "name",
    "parent_region_id",
    "population",
    "boundary_ref",
    "centroid",
  ],
  consentRecordFixture: [
    "consent_id",
    "citizen_id",
    "purpose",
    "consent_text_version",
    "language_shown",
    "granted_at",
    "channel",
    "withdrawn_at",
  ],
  citizenFixture: [
    "citizen_id",
    "phone_hash",
    "preferred_language",
    "country_code",
    "created_at",
    "erasure_requested_at",
  ],
  submissionFixture: [
    "submission_id",
    "idempotency_key",
    "citizen_id",
    "country_code",
    "channel",
    "raw_text",
    "raw_audio_url",
    "photo_url",
    "detected_language",
    "translated_text",
    "pii_scrubbed_text",
    "lat",
    "lng",
    "location_text",
    "location_confidence",
    "geohash",
    "resolved_region_id",
    "state_id",
    "issue_id",
    "submitted_at",
    "status",
    "processing_error",
  ],
  issueFixture: [
    "issue_id",
    "country_code",
    "state_id",
    "category",
    "subcategory",
    "canonical_description",
    "embedding",
    "embedding_model",
    "geo_cluster_id",
    "admin_region_id",
    "geohash",
    "submission_ids",
    "report_count",
    "distinct_reporter_count",
    "first_reported_at",
    "last_reported_at",
    "emergency_override",
    "fraud_flags",
    "status",
  ],
  geoClusterFixture: [
    "cluster_id",
    "country_code",
    "state_id",
    "admin_region_id",
    "centroid_lat",
    "centroid_lng",
    "geohash",
    "radius_m",
    "issue_ids",
  ],
  infraIndexFixture: [
    "region_id",
    "country_code",
    "state_id",
    "index_type",
    "value",
    "normalised_value",
    "source",
    "source_url",
    "licence",
    "year",
  ],
  investmentRecordFixture: [
    "investment_id",
    "region_id",
    "country_code",
    "state_id",
    "scheme_name",
    "scheme_id",
    "amount",
    "currency",
    "category",
    "fiscal_year",
    "sanctioned_at",
    "data_origin",
  ],
  priorityScoreFixture: [
    "score_id",
    "issue_id",
    "country_code",
    "state_id",
    "demand_score",
    "vulnerability_score",
    "gap_score",
    "duplication_penalty",
    "impact_efficacy",
    "base_score",
    "composite_score",
    "weights",
    "data_fallbacks",
    "model_version",
    "computed_at",
    "is_canonical",
  ],
  projectFixture: [
    "project_id",
    "issue_id",
    "country_code",
    "state_id",
    "generated_brief",
    "brief_model_version",
    "brief_citations",
    "groundedness_check",
    "composite_score",
    "status",
    "assigned_dept",
    "budget_estimate_inr",
  ],
  impactRecordFixture: [
    "impact_id",
    "project_id",
    "issue_id",
    "country_code",
    "state_id",
    "category",
    "region_id",
    "confirmations_received",
    "confirmations_required",
    "confirmations_negative",
    "resolution_photo_url",
    "resolved_at",
    "verified_by",
    "efficacy",
  ],
  officerUserFixture: [
    "officer_id",
    "name",
    "role",
    "country_code",
    "region_id",
    "auth_provider_id",
    "state_id",
  ],
  agentSessionFixture: [
    "session_id",
    "officer_id",
    "country_code",
    "state_id",
    "region_scope",
    "started_at",
    "turn_count",
  ],
  agentTurnFixture: [
    "turn_id",
    "session_id",
    "query_text",
    "tool_calls",
    "agent_response",
    "citations",
    "refused",
    "refusal_reason",
    "prompt_version",
    "total_latency_ms",
    "timestamp",
  ],
};

describe("shared-types fixtures match DATA_MODEL.md field sets", () => {
  for (const [name, keys] of Object.entries(expectedKeys)) {
    it(`${name} has exactly the expected fields`, () => {
      const fixture = (fixtures as Record<string, object>)[name];
      expect(Object.keys(fixture).sort()).toEqual([...keys].sort());
    });
  }
});
